#!/usr/bin/env python3
"""
g-xTB v2 wrapper compatible with ORCA's ExtTool interface.

The current upstream g-xTB distribution is a modified ``xtb`` executable that is
invoked with ``--gxtb``. This calculator lets ORCA drive optimizations,
transition-state searches, NEB, MD, and related workflows while g-xTB supplies
energies and gradients through OET's standard ``.engrad`` contract.
"""

import os
from argparse import ArgumentParser
from pathlib import Path
from typing import Any

from oet.core.base_calc import BaseCalc, CalculationData
from oet.core.misc import check_path, mult_to_nue, nat_from_xyzfile, run_command


class GxtbCalc(BaseCalc):
    @property
    def PROGRAM_NAMES(self) -> list[str] | None:
        """Do not auto-detect regular xtb; g-xTB v2 must be explicit."""
        return None

    @classmethod
    def extend_parser(cls, parser: ArgumentParser) -> None:
        """Add g-xTB v2 parsing options."""
        parser.add_argument(
            "-x",
            "--exe",
            dest="prog",
            help="Path to the g-xTB v2 xtb executable. Defaults to GXTB_EXE.",
        )

    @staticmethod
    def resolve_gxtb_executable(prog: str | None) -> str | None:
        """Return the requested executable or the GXTB_EXE environment value."""
        return prog or os.getenv("GXTB_EXE")

    @staticmethod
    def gxtb_command_args(calc_data: CalculationData, extra_args: list[str]) -> list[str]:
        """Build the g-xTB v2 command-line arguments."""
        args = [
            str(calc_data.xyzfile),
            "--gxtb",
            "--chrg",
            str(calc_data.charge),
            "--uhf",
            str(mult_to_nue(calc_data.mult)),
            "--parallel",
            str(calc_data.ncores),
            "--namespace",
            calc_data.basename,
        ]
        if calc_data.dograd:
            args.append("--grad")
        return args + extra_args

    def run_gxtb(self, calc_data: CalculationData, args: list[str]) -> None:
        """Run the g-xTB v2 xtb executable."""
        os.environ["OMP_NUM_THREADS"] = str(calc_data.ncores)

        if calc_data.pointcharges:
            raise NotImplementedError(
                "g-xTB v2 point-charge handling through OET is not implemented."
            )
        if not calc_data.prog_path:
            raise RuntimeError("Path to g-xTB v2 xtb executable is None.")

        run_command(
            calc_data.prog_path,
            calc_data.output_file,
            self.gxtb_command_args(calc_data=calc_data, extra_args=args),
        )

    @staticmethod
    def read_energy(energy_file: str | Path) -> float:
        """Read total energy from a g-xTB v2 namespace .energy file."""
        energy_path = check_path(energy_file)
        with energy_path.open() as f:
            lines = f.readlines()

        for i, line in enumerate(lines):
            if line.strip() == "$energy":
                return float(lines[i + 1].split()[1])
        raise ValueError(f"Energy couldn't be found in {energy_path}.")

    @staticmethod
    def read_gradient(gradient_file: str | Path, natoms: int) -> list[float]:
        """Read flattened gradient from a g-xTB v2 namespace .gradient file."""
        grad_path = check_path(gradient_file)
        gradient: list[float] = []
        natoms_read = 0
        with grad_path.open() as f:
            for line in f:
                if "$grad" in line:
                    break
            for line in f:
                fields = line.split()
                if len(fields) == 4:
                    natoms_read += 1
                elif len(fields) == 3:
                    gradient.extend(float(i.replace("D", "E")) for i in fields)
                elif "$end" in line:
                    break

        if natoms_read != natoms:
            raise ValueError(
                f"Number of atoms read: {natoms_read} does not match expected {natoms}."
            )
        if len(gradient) != 3 * natoms:
            raise ValueError(
                f"Gradient entries: {len(gradient)} does not match 3x atoms: {natoms}."
            )
        return gradient

    def read_gxtb_results(self, calc_data: CalculationData, natoms: int) -> tuple[float, list[float]]:
        """Read g-xTB v2 namespace files generated by xtb."""
        energy = self.read_energy(f"{calc_data.basename}.energy")
        gradient = []
        if calc_data.dograd:
            gradient = self.read_gradient(f"{calc_data.basename}.gradient", natoms=natoms)
        return energy, gradient

    def calc(
        self,
        calc_data: CalculationData,
        args_parsed: dict[str, Any],
        args_not_parsed: list[str],
    ) -> tuple[float, list[float]]:
        """Compute energy and optional gradient for ORCA."""
        prog = self.resolve_gxtb_executable(args_parsed.get("prog"))
        calc_data.set_program_path(prog)
        if calc_data.prog_path:
            print(f"Using executable {calc_data.prog_path}")
        else:
            raise FileNotFoundError(
                "Could not find a valid g-xTB v2 xtb executable. "
                "Set GXTB_EXE or pass --exe."
            )

        self.run_gxtb(calc_data=calc_data, args=args_not_parsed)
        natoms = nat_from_xyzfile(xyz_file=calc_data.xyzfile)
        return self.read_gxtb_results(calc_data=calc_data, natoms=natoms)


def main() -> None:
    """Main routine for execution."""
    calculator = GxtbCalc()
    inputfile, args, args_not_parsed = calculator.parse_args()
    calculator.run(inputfile=inputfile, args_parsed=args, args_not_parsed=args_not_parsed)


if __name__ == "__main__":
    main()
